language: python
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

python:
- 3.6

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    # - mypy . --ignore-missing-imports  # need new mypy version
    after_success:
    - pytest --cov
    - coveralls
# just saving travis-ci resources
#  - os: osx
#    language: sh
#    install: pip3 install -e .[tests]

install: pip install -e .[tests]

script: pytest -rsv